#!/usr/bin/env perl

use 5.008008;

use strict;
use warnings;

use App::AckX::Preflight;

our $VERSION = '0.000_015';

App::AckX::Preflight->run();

__END__

=head1 TITLE

ackxp - Ad-hoc preflight munging of F<ack>'s arguments.

=head1 SYNOPSIS

 ackxp -w foo
 ackxp -help
 ackxp -version

=head1 OPTIONS

The following options are interpreted directly. Others may be
interpreted by plug-ins or by F<ack>. See the relevant documentation for
these.

=head2 -ack-filters

This option enables or disables ack-style file filtering for plug-ins
that use it.

The default is C<-ack-filters> if ack-style filtering is available, and
C<-no-ack-filters> otherwise. The main anticipated use of this option is
turning the filter code off if it causes trouble.

=head2 -help

This option displays the documentation for this script. The script then
exits.

You can provide the following optional arguments:

=over

=item C<'config'>

This argument causes all the configuration files that would be used to
be displayed. The script then exits.

=item C<'plugins'>

This argument causes the installed plugins to be listed. The script then
exits.

=item plugin name

If the argument is a name from the list provided by C<'plugins'>, the
documentation for that plugin is displayed. The script then exits.

=back

Any other argument is an error.

=head2 -man

This option is a synonym for L<-help|/-help>.

=head2 -version

This option displays the version of this script. The script then exits.

=head1 DETAILS

This Perl script simply loads
L<App::AckX::Preflight|App::AckX::Preflight> and calls its
L<run()|App::AckX::Preflight/run> method. This method loads whatever
plugins are installed, and calls them to modify the command arguments as
they see fit. Then it passes control to the F<ack> script.

No, none of this makes F<ack> do anything it would not have done before.
But it can come close. A plug-in could do something like load patterns
from a file, or restrict the search to files whose names appear in a
F<MANIFEST>. At this level it's really an exercise in imagination.

=head1 AUTHOR

Thomas R. Wyant, III F<wyant at cpan dot org>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2018 by Thomas R. Wyant, III

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl 5.10.0. For more details, see the full text
of the licenses in the directory LICENSES.

This program is distributed in the hope that it will be useful, but
without any warranty; without even the implied warranty of
merchantability or fitness for a particular purpose.

=cut

# ex: set textwidth=72 :
