#!/usr/bin/env perl

use 5.008008;

use strict;
use warnings;

use Getopt::Long 2.33 qw{ :config auto_version };
use Pod::Usage;

use lib qw{ inc };
use My::Module::TestSyntax;

our $VERSION = '0.000_040';

my %opt;

GetOptions( \%opt,
    help => sub { pod2usage( { -verbose => 2 } ) },
) and @ARGV < 2 or pod2usage( { -verbose => 0 } );

my $fh;
if ( @ARGV ) {
    open $fh, '<', $ARGV[0]
	or die "Failed to open $ARGV[0]: $!\n";
} else {
    $fh = \*STDIN;
}

print slurp( $fh );

__END__

=head1 TITLE

number - Number the lines of files consistently with t/syntax_*.t

=head1 SYNOPSIS

 number <foo
 number foo
 number -help
 number -version

=head1 OPTIONS

=head2 -help

This option displays the documentation for this script. The script then
exits.

=head2 -version

This option displays the version of this script. The script then exits.

=head1 DETAILS

This Perl script prints a file to standard out, with lines numbered
consistently with the usage in F<t/syntax_*.t>. The file name is given
on the command line. If there is none, C<STDIN> is read.

This script must be run from the home directory of this package, because
it makes use of C<My::Module::TestSyntax>, which is in the F<inc/>
directory of the package.

This Perl script is completely unsupported, and may be changed or
removed without notice.

=head1 AUTHOR

Thomas R. Wyant, III F<wyant at cpan dot org>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2018-2022 by Thomas R. Wyant, III

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl 5.10.0. For more details, see the full text
of the licenses in the directory LICENSES.

This program is distributed in the hope that it will be useful, but
without any warranty; without even the implied warranty of
merchantability or fitness for a particular purpose.

=cut

# ex: set textwidth=72 :
